<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VeterinariaDrFabio.Dominio\VeterinariaDrFabio.Dominio.csproj" />
    <ProjectReference Include="..\VeterinariaDrFabio.Datos\VeterinariaDrFabio.Datos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.9.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
